version: '3.7'
services:
  app:
    image: 
    container_name: fage-app
    env_file: ./.env
    ports:
      - "8000:8000"
    environment: 
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_KEY=$AWS_SECRET_KEY
      - S3_BUCKET=$S3_BUCKET
      - PORT=$PORT
      - COOKIE_SECRET=$COOKIE_SECRET
      - KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
      - KAKAO_CLIENT_SECRET=$KAKAO_CLIENT_SECRET
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - NAVER_CLIENT_ID=$NAVER_CLIENT_ID
      - NAVER_CLIENT_SECRET=$NAVER_CLIENT_SECRET
      - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASENAME=$MYSQL_DATABASENAME
      - PIXABAY_KEY=$PIXABAY_KEY
      - REDIS_PORT=$REDIS_PORT
      - REDIS_HOST=$REDIS_HOST
    networks: 
      - fage-net

networks: 
  fage-net: